name: Deploy to prod.

on:
  push:
    branches: [main]

jobs:
  do-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: RunHello
        run: bash ${GITHUB_WORKSPACE}/run.sh
        shell: bash
  remote-connect:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: 22
          script: sh run.sh
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Test with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: test
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . --tag vilichtsarina/m223:sarinabackend && docker push vilichtsarina/m223:sarinabackend