name: Deploy to prod.

on:
  push:
    branches: [main]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello World"
  say-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Secret
        run: echo ${{secrets.HANS}}
  do-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: RunHello
        run: bash ${GITHUB_WORKSPACE}/run.sh
        shell: bash
  remote-connect:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: 22
          run: ./run.sh
          shell: bash
